{% set name = "uproot-methods" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 606bc45672bb76c176d6469aebf72f7be0010b26ce95b7aec63b2c09780bf8d1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.13.1
    - awkward >=0.9.0

test:
  imports:
    - uproot_methods

about:
  home: https://github.com/scikit-hep/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Pythonic behaviors for non-I/O related ROOT classes.'
  dev_url: https://github.com/scikit-hep/{{ name }}

extra:
  recipe-maintainers:
    - chrisburr
    - jpivarski
